name: Gradle build & ktLintCheck

on:
  pull_request:
    branches: [ "main", "dev", "backend" ]
    
defaults:
  run:
    working-directory: backend/ktor-backend

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.3.3
      
    - name: Execute Gradle build
      run: gradle build
      
    - name: Execute Gradle ktlintCheck
      run: gradle ktlintCheck
