name: Gradle build & ktLintCheck

on:
  push:
    branches: [ "main", "backend" ]
  pull_request:
    branches: [ "main", "backend" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.3.3
      
    - name: Execute Gradle build
      run: ./gradlew build
      
    - name: Execute Gradle ktlintCheck
      run: ./gradlew ktlintCheck
